/*
 * This file is generated by jOOQ.
 */
package com.zlargon.springdemo.jooq.tables.references

import com.zlargon.springdemo.jooq.tables.Book

/**
 * The table <code>spring_demo.book</code>.
 */
val BOOK: Book = Book.BOOK
