/*
 * This file is generated by jOOQ.
 */
package com.zlargon.springdemo.jooq.keys

import com.zlargon.springdemo.jooq.tables.Book
import com.zlargon.springdemo.jooq.tables.records.BookRecord
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal

// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val BOOK_PKEY: UniqueKey<BookRecord> = Internal.createUniqueKey(Book.BOOK, DSL.name("book_pkey"), arrayOf(Book.BOOK.ID), true)
