#!/bin/bash
set -e

# if this fails, please run mvn ktlint:format to reformat
echo '[pre-commit] Ktlint check the code format "mvn ktlint:check" ...'
if ! mvn -q ktlint:check; then
  echo_r "\n[ERROR] format check failed."
  echo -e "Please run \"mvn ktlint:format\" to reformat\n"
  exit 1
fi

echo "[pre-commit] ktlint check ok"
