/*
 * This file is generated by jOOQ.
 */
package com.zlargon.springdemo.jooq

import org.jooq.Schema
import org.jooq.impl.CatalogImpl
import kotlin.collections.List

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DefaultCatalog : CatalogImpl("") {
  companion object {

    /**
     * The reference instance of <code>DEFAULT_CATALOG</code>
     */
    public val DEFAULT_CATALOG: DefaultCatalog = DefaultCatalog()
  }

  /**
   * The schema <code>spring_demo</code>.
   */
  val SPRING_DEMO: SpringDemo get(): SpringDemo = SpringDemo.SPRING_DEMO

  override fun getSchemas(): List<Schema> = listOf(
    SpringDemo.SPRING_DEMO
  )
}
