/*
 * This file is generated by jOOQ.
 */
package com.zlargon.springdemo.jooq

import com.zlargon.springdemo.jooq.tables.Book
import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl
import kotlin.collections.List

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SpringDemo : SchemaImpl("spring_demo", DefaultCatalog.DEFAULT_CATALOG) {
  public companion object {

    /**
     * The reference instance of <code>spring_demo</code>
     */
    val SPRING_DEMO: SpringDemo = SpringDemo()
  }

  /**
   * The table <code>spring_demo.book</code>.
   */
  val BOOK: Book get() = Book.BOOK

  override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

  override fun getTables(): List<Table<*>> = listOf(
    Book.BOOK
  )
}
